### PR TITLE
fixes #25: Add tool to send raw XMPP

### LINKED ISSUE #25: Add tool to send raw XMPP
It will be useful to have a tool that takes a simple text input, and sends that as XMPP data.

### PR DESCRIPTION
**Pull request by guusdk**
A new page (under 'sessions' > 'tools' > 'raw xmpp sender') is added, that allows an administrator to send XMPP data.

image

### CODE REVIEW

**Comment by akrherz** [comment]
Fancy!  What about adding a HTML select pulldown that allowed the admin to select an existing s2s or c2s connection to inject that stanza into.  Could be useful for testing situations when you want to see what a client does when provided a given stanza from the server, for example.

**Comment by guusdk** [comment]
Seems like a nice addition. I would also like to have some way to provide stanza templates for commonly-used stanzas (ping, disco#info, a simple message, etc).

**Comment by guusdk** [comment]
This confusingly (I made a mess of things) now adds support for Openfire 4.8.0).

**Comment by guusdk** [comment]
I have created #29 and #30 for the new feature requests.

**Review by akrherz — APPROVED** [review]

**Pull request merged**
